# Generated by Django 6.0.3 on 2026-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicavet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
