# Generated by Django 6.0.3 on 2026-05-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicavet', '0002_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
    ]
