# Generated by Django 6.0.4 on 2026-05-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicavet', '0003_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20),
        ),
    ]
